version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: ${image}
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${db_username}
      WORDPRESS_DB_PASSWORD: ${db_password}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: ${wp_debug}
      WORDPRESS_CONFIG_EXTRA: define( 'WP_HOME', 'http://${site_domain}/' ); define( 'WP_SITEURL', 'http://${site_domain}/' ); define( 'WP_DEBUG_LOG', ${wp_debug_log} ); ${wp_extra}
    volumes:
      - wordpress:/var/www/html

  db:
    container_name: db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${db_username}
      MYSQL_PASSWORD: ${db_password}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
